config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'users/:id' => "users#show", as: "show_user"

  get 'keywords/index'

  get 'comments/create'

  root 'bulbs#index'

  match "/auth/:provider/callback" => "sessions#create", via: [:get, :post]
  match "/signout" => "sessions#destroy", :as => :signout, via: [:get, :post]

  get "/keywords" => "keywords#index"

  resources :shops
  resources :services
  get 'static_pages/welcome'

  resources :bulbs
  resources :comments
  resources :apps
  resources :platforms

end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  before_action :set_platform, only: [:show, :edit, :update, :destroy]

  # GET /platforms
  # GET /platforms.json
  def index
    @platforms = Platform.all
  end

  # GET /platforms/1
  # GET /platforms/1.json
  def show
  end

  # GET /platforms/new
  def new
    @platform = Platform.new
  end

  # GET /platforms/1/edit
  def edit
  end

  # POST /platforms
  # POST /platforms.json
  def create
    @platform = Platform.new(platform_params)
    @platform.save

    @bulb = Bulb.new
    @bulb.title = params[:platform][:title]
    @bulb.description = params[:platform][:description]
    @bulb.target1 = params[:platform][:target1]
    @bulb.target2 = params[:platform][:target2]
    @bulb.category = "platform"
    @bulb.ref_id = @platform.id
        @bulb.user_id = current_user.id
    @bulb.save

      @platform.bulb_id = @bulb.id
     @platform.save

    uri = URI.parse("https://api.monkeylearn.com/v2/extractors/ex_y7BPYzNG/extract/")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    request = Net::HTTP::Post.new(uri.request_uri)
    # Set POST data
    request.body = {text_list: [@bulb.description]}.to_json
    request.add_field("Content-Type", "application/json")
    request.add_field("Authorization", "token c956c6be34d90185c5eab3c04a8f58416259aa67")
    # parse the monkeylearn respons
    response = JSON.parse http.request(request).body
    response_array = response["result"].first

    keywords = Array.new

    response_array.each do |response|
      keywords << response["keyword"]
    end

    keywords.each do |keyword|
      k = Keyword.new
      k.bulb_id = @bulb.id
      k.content = keyword
      k.save
    end

    picture_results = Unsplash::Photo.search(keywords.sample)
      if picture_results.count != 0
        picture_sample = picture_results.sample
        @bulb.picture = picture_sample.urls["small"]
        @bulb.big_picture = picture_sample.urls["regular"]
        @bulb.save
        @platform.picture = @bulb.picture
        @platform.save
    end

    respond_to do |format|
      if @platform.save
        format.html { redirect_to bulbs_url }
        format.json { render :show, status: :created, location: @platform }
      else
        format.html { render :new }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /platforms/1
  # PATCH/PUT /platforms/1.json
  def update

    @platform.update(platform_params)
    @platform.save

    @bulb = Bulb.find_by(:id => @platform.bulb_id)
    @bulb.title = params[:platform][:title]
    @bulb.description = params[:platform][:description]
    @bulb.target1 = params[:platform][:target1]
    @bulb.target2 = params[:platform][:target2]
    @bulb.category = "platform"
    @bulb.ref_id = @platform.id
    @bulb.user_id = current_user.id
    @bulb.save


    uri = URI.parse("https://api.monkeylearn.com/v2/extractors/ex_y7BPYzNG/extract/")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    request = Net::HTTP::Post.new(uri.request_uri)
    # Set POST data
    request.body = {text_list: [@bulb.description]}.to_json
    request.add_field("Content-Type", "application/json")
    request.add_field("Authorization", "token c956c6be34d90185c5eab3c04a8f58416259aa67")
    # parse the monkeylearn respons
    response = JSON.parse http.request(request).body
    response_array = response["result"].first

    keywords = Array.new

    response_array.each do |response|
      keywords << response["keyword"]
    end

    keywords.each do |keyword|
      k = Keyword.new
      k.bulb_id = @bulb.id
      k.content = keyword
      k.save
    end


    respond_to do |format|
      if @platform.save
        format.html { redirect_to bulbs_url }
        format.json { render :show, status: :created, location: @platform }
      else
        format.html { render :new }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /platforms/1
  # DELETE /platforms/1.json
  def destroy
    @platform.destroy
    respond_to do |format|
      format.html { redirect_to platforms_url, notice: 'Platform was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_platform
      @platform = Platform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def platform_params
      params.require(:platform).permit(:title, :target1, :target2, :description, :gain1, :gain2, :picture, :big_picture, :bulb_id)
    end
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/views/platforms/_form.html.erb
<%= form_for(@platform) do |f| %>
  <% if @platform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@platform.errors.count, "error") %> prohibited this platform from being saved:</h2>

      <ul>
      <% @platform.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <h4><%= f.text_field(:title, :class => "comment_input",:placeholder => "NAME YOUR BULB (eg. AIRBNB)") %></h4>
  <h4>is a <span class="bulb_type">PLATFORM</span> that connects</h4>
  <h4><%= f.text_field(:target1, :class => "comment_input",:placeholder => "DEFINE AUDIENCE 1" ) %></h4>
  <h4 style="padding-left: 250px"><span class="bulb_type">+</span></h4>
  <h4><%= f.text_field(:target2, :class => "comment_input",:placeholder => "DEFINE AUDIENCE 2" ) %></h4>
  <h4><%= f.text_area(:description, :class => "text_area_small2", :placeholder => "Decribe it in your own words.") %></h4>
  <%= f.submit("CREATE BULB", :class => "submit_button comment_button", data: {disable_with: "Starting Machine Learning..."}) %>


<% end %>

app/views/platforms/edit.html.erb
<div class="row">


<div class="col-sm-12">

<h1 id="add_platform_title" style="font-family: 'Mr Dafoe', cursive; font-size: 80px; letter-spacing: 1px; text-align: center; padding: 0px 60px 0px 60px; font-weight: bolder; margin-top: 0px; margin-bottom: 0px; line-height: 90px; color: white">Your bulb's title</h1>

</div>

</div>

<div class="row">

<div class="grid-item2 col-sm-8 col-sm-offset-2" style="margin-top: 20px; padding: 90px">

  <%= render 'form' %>



</div>

</div>

<script type="text/javascript">
  $(function() {
    $("#platform_title").focusout( function(e) {
    var content = e.target.value
    $('#add_platform_title').text(content);

    });
  });
</script>

app/views/platforms/index.html.erb
<div class="">

<div class="grid">
<div class="grid-sizer"></div>
<% @platforms.reverse.each do |platform| %>
    <div class="grid-item">

      <% if platform.picture != nil %>
      <div class="row bulb_hl">
        <img src="<%= platform.picture %>" width="100%">
      </div>
      <% end %>

      <div class="row bulb_hl" style="padding-top: 0px; padding-bottom: 0px">
        <div class="col-xs-12" style="padding: 0px;">
          <h4 style="margin-bottom: 0px;" class="index_mega"><span style="width: 100%"><%= platform.title %></span></h4>
<!--           <img src="http://40.media.tumblr.com/4acc2a446cc63f3a52353a6c673391b1/tumblr_nm6y9hzrla1roigg6o1_1280.png" width="100%" style="margin-bottom: 20px;"> -->
        </div>
      </div>

      <div class="row bulb_hl" style="padding-top: 0px">
          <div class="col-xs-3" style="padding-left: 0px;">
            <h4 style="margin-bottom: 0px; padding-top: 30px;">is a</h4>
          </div>
          <div class="col-xs-9" style="padding-left: 0px; padding-right: 0px;">
            <h4 style="margin-bottom: 0px; margin-top: 20px;" class="index_mega_color_platform"><span>PLATFORM</span></h4>
          </div>
      </div>

      <div class="row bulb_hl" style="padding-top: 0px; padding-bottom: 0px">
        <h4 style="margin-bottom: 20px; padding-top: 0px; margin-top: 0px">that connects</h4>
        <h4 class="index_mega"><span ><%= platform.target1 %></span></h4>
        <h4 style="margin-bottom: 20px; padding-top: 10px; margin-top: 0px">and</h4>
        <h4 class="index_mega" style="margin: 20px 0px 0px 0px;"><%= platform.target2 %></h4>
      </div>


    </div>
<% end %>


</div>


</div>



<div class="fut" style="display: none">

<p id="notice"><%= notice %></p>

<h1>Listing Platforms</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Target1</th>
      <th>Target2</th>
      <th>Description</th>
      <th>Gain1</th>
      <th>Gain2</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @platforms.each do |platform| %>
      <tr>
        <td><%= platform.title %></td>
        <td><%= platform.target1 %></td>
        <td><%= platform.target2 %></td>
        <td><%= platform.description %></td>
        <td><%= platform.gain1 %></td>
        <td><%= platform.gain2 %></td>
        <td><%= platform.picture %></td>
        <td><%= link_to 'Show', platform %></td>
        <td><%= link_to 'Edit', edit_platform_path(platform) %></td>
        <td><%= link_to 'Destroy', platform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Platform', new_platform_path %>
</div>

app/views/platforms/new.html.erb
<div class="row">


<div class="col-sm-12">

<h1 id="add_platform_title" style="font-family: 'Mr Dafoe', cursive; font-size: 80px; letter-spacing: 1px; text-align: center; padding: 0px 60px 0px 60px; font-weight: bolder; margin-top: 0px; margin-bottom: 0px; line-height: 90px; color: white">Your bulb's title</h1>

</div>

</div>

<div class="row">

<div class="grid-item2 col-sm-8 col-sm-offset-2" style="margin-top: 20px; padding: 90px">

  <%= render 'form' %>



</div>

</div>

<script type="text/javascript">
  $(function() {
    $("#platform_title").focusout( function(e) {
    var content = e.target.value
    $('#add_platform_title').text(content);

    });
  });
</script>

app/views/platforms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @platform.title %>
</p>

<p>
  <strong>Target1:</strong>
  <%= @platform.target1 %>
</p>

<p>
  <strong>Target2:</strong>
  <%= @platform.target2 %>
</p>

<p>
  <strong>Description:</strong>
  <%= @platform.description %>
</p>

<p>
  <strong>Gain1:</strong>
  <%= @platform.gain1 %>
</p>

<p>
  <strong>Gain2:</strong>
  <%= @platform.gain2 %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @platform.picture %>
</p>

<%= link_to 'Edit', edit_platform_path(@platform) %> |
<%= link_to 'Back', platforms_path %>