config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'users/:id' => "users#show", as: "show_user"

  get 'keywords/index'

  get 'comments/create'

  root 'bulbs#index'

  match "/auth/:provider/callback" => "sessions#create", via: [:get, :post]
  match "/signout" => "sessions#destroy", :as => :signout, via: [:get, :post]

  get "/keywords" => "keywords#index"

  resources :shops
  resources :services
  get 'static_pages/welcome'

  resources :bulbs
  resources :comments
  resources :apps
  resources :platforms

end

app/models/shop.rb
class Shop < ActiveRecord::Base
    belongs_to :bulb
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)
    @shop.save

    @bulb = Bulb.new
    @bulb.title = params[:shop][:title]
    @bulb.description = params[:shop][:description]
    @bulb.target = params[:shop][:target]
    @bulb.category = "shop"
    @bulb.ref_id = @shop.id
    @bulb.user_id = current_user.id
    @bulb.save

     @shop.bulb_id = @bulb.id
     @shop.save

    uri = URI.parse("https://api.monkeylearn.com/v2/extractors/ex_y7BPYzNG/extract/")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    request = Net::HTTP::Post.new(uri.request_uri)
    # Set POST data
    request.body = {text_list: [@bulb.description]}.to_json
    request.add_field("Content-Type", "application/json")
    request.add_field("Authorization", "token c956c6be34d90185c5eab3c04a8f58416259aa67")
    # parse the monkeylearn respons
    response = JSON.parse http.request(request).body
    response_array = response["result"].first

    keywords = Array.new

    response_array.each do |response|
      keywords << response["keyword"]
    end

    keywords.each do |keyword|
      k = Keyword.new
      k.bulb_id = @bulb.id
      k.content = keyword
      k.save
    end

    picture_results = Unsplash::Photo.search(keywords.sample)
      if picture_results.count != 0
        picture_sample = picture_results.sample
        @bulb.picture = picture_sample.urls["small"]
        @bulb.big_picture = picture_sample.urls["regular"]
        @bulb.save
        @shop.picture = @bulb.picture
        @shop.save
    end

    respond_to do |format|
      if @shop.save
        format.html { redirect_to bulbs_url }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    @shop.update(shop_params)
    @shop.save

    @bulb = Bulb.find_by(:id => @shop.bulb_id)
    @bulb.title = params[:shop][:title]
    @bulb.description = params[:shop][:description]
    @bulb.target = params[:shop][:target]
    @bulb.category = "shop"
    @bulb.ref_id = @shop.id
    @bulb.user_id = current_user.id
    @bulb.save

    uri = URI.parse("https://api.monkeylearn.com/v2/extractors/ex_y7BPYzNG/extract/")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    request = Net::HTTP::Post.new(uri.request_uri)
    # Set POST data
    request.body = {text_list: [@bulb.description]}.to_json
    request.add_field("Content-Type", "application/json")
    request.add_field("Authorization", "token c956c6be34d90185c5eab3c04a8f58416259aa67")
    # parse the monkeylearn respons
    response = JSON.parse http.request(request).body
    response_array = response["result"].first

    keywords = Array.new

    response_array.each do |response|
      keywords << response["keyword"]
    end

    keywords.each do |keyword|
      k = Keyword.new
      k.bulb_id = @bulb.id
      k.content = keyword
      k.save
    end


    respond_to do |format|
      if @shop.save
        format.html { redirect_to bulbs_url }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:title, :target, :description, :picture, :big_picture, :bulb_id)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h4><%= f.text_field(:title, :class => "comment_input",:placeholder => "NAME YOUR BULB (eg. BULBZ)") %></h4>
  <h4>is a <span class="bulb_type">SHOP</span> that sells</h4>
  <h4><%= f.text_area(:description, :class => "text_area_small2", :placeholder => "Decribe what the shop sells in your own words.") %></h4>
  <h4>to</h4>
  <h4><%= f.text_field(:target, :class => "comment_input", :placeholder => "DEFINE AN AUDIENCE (eg. IDEA JUNKIES)") %></h4>
  <%= f.submit("CREATE BULB", :class => "submit_button comment_button", data: {disable_with: "Starting Machine Learning..."}) %>
<% end %>

app/views/shops/edit.html.erb
<div class="row">


<div class="col-sm-12">

<h1 id="add_shop_title" style="font-family: 'Mr Dafoe', cursive; font-size: 80px; letter-spacing: 1px; text-align: center; padding: 0px 60px 0px 60px; font-weight: bolder; margin-top: 0px; margin-bottom: 0px; line-height: 90px; color: white">Your bulb's title</h1>

</div>

</div>

<div class="row">

<div class="grid-item2 col-sm-8 col-sm-offset-2" style="margin-top: 20px; padding: 90px">

  <%= render 'form' %>



</div>

</div>

<script type="text/javascript">


  $(function() {
  $("#shop_title").focusout( function(e) {
    var content = e.target.value
    $('#add_shop_title').text(content);

    });

  });
</script>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shops</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Target</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.title %></td>
        <td><%= shop.target %></td>
        <td><%= shop.description %></td>
        <td><%= shop.picture %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<div class="row">


<div class="col-sm-12">

<h1 id="add_shop_title" style="font-family: 'Mr Dafoe', cursive; font-size: 80px; letter-spacing: 1px; text-align: center; padding: 0px 60px 0px 60px; font-weight: bolder; margin-top: 0px; margin-bottom: 0px; line-height: 90px; color: white">Your bulb's title</h1>

</div>

</div>

<div class="row">

<div class="grid-item2 col-sm-8 col-sm-offset-2" style="margin-top: 20px; padding: 90px">

  <%= render 'form' %>



</div>

</div>

<script type="text/javascript">


  $(function() {
  $("#shop_title").focusout( function(e) {
    var content = e.target.value
    $('#add_shop_title').text(content);

    });

  });
</script>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @shop.title %>
</p>

<p>
  <strong>Target:</strong>
  <%= @shop.target %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shop.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @shop.picture %>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>