config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'users/:id' => "users#show", as: "show_user"

  get 'keywords/index'

  get 'comments/create'

  root 'bulbs#index'

  match "/auth/:provider/callback" => "sessions#create", via: [:get, :post]
  match "/signout" => "sessions#destroy", :as => :signout, via: [:get, :post]

  get "/keywords" => "keywords#index"

  resources :shops
  resources :services
  get 'static_pages/welcome'

  resources :bulbs
  resources :comments
  resources :apps
  resources :platforms

end

app/models/app.rb
class App < ActiveRecord::Base
  belongs_to :bulb
end

app/models/bulb.rb
class Bulb < ActiveRecord::Base
  belongs_to :user
  belongs_to :app
  belongs_to :shop
  belongs_to :service
  belongs_to :platform
  has_many :comments
  has_many :keywords

end

app/models/comment.rb
require "net/http"
require "uri"
require 'json'

class Comment < ActiveRecord::Base
  belongs_to :bulb
  belongs_to :user

  def keyword_generator
    uri = URI.parse("https://api.monkeylearn.com/v2/extractors/ex_y7BPYzNG/extract/")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    request = Net::HTTP::Post.new(uri.request_uri)
    # Set POST data
    request.body = {text_list: [self.content]}.to_json
    request.add_field("Content-Type", "application/json")
    request.add_field("Authorization", "token c956c6be34d90185c5eab3c04a8f58416259aa67")
    # parse the monkeylearn respons
    response = JSON.parse http.request(request).body
    response_array = response["result"].first

    keywords = Array.new

    response_array.each do |response|
      keywords << response["keyword"]
    end

    bulb = Bulb.find_by(:id => self.bulb_id)

    keywords.each do |keyword|
      k = Keyword.new
      k.bulb_id = bulb.id
      k.content = keyword
      k.save
    end

  end

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  belongs_to :bulb
end

app/models/platform.rb
class Platform < ActiveRecord::Base
    belongs_to :bulb
end

app/models/service.rb
class Service < ActiveRecord::Base
    belongs_to :bulb
end

app/models/shop.rb
class Shop < ActiveRecord::Base
    belongs_to :bulb
end

app/models/user.rb
class User < ActiveRecord::Base

    has_many :bulbs
    has_many :comments

    def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.email = auth["info"]["email"]
      user.profile_picture = auth["info"]["image"] + "?width=600&height=600"
    end
  end
end

app/controllers/apps_controller.rb
require "net/http"
require "uri"
require 'json'

class AppsController < ApplicationController
  before_action :set_app, only: [:show, :edit, :update, :destroy]

  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
  end

  # GET /apps/new
  def new
    @app = App.new
  end

  # GET /apps/1/edit
  def edit
  end

  # POST /apps
  # POST /apps.json
  def create

    @app = App.new(app_params)
    @app.save

    @bulb = Bulb.new
    @bulb.title = params[:app][:title]
    @bulb.description = params[:app][:description]
    @bulb.target = params[:app][:target]
    @bulb.category = "app"
    @bulb.ref_id = @app.id
    @bulb.user_id = current_user.id
    @bulb.save

    @app.bulb_id = @bulb.id
    @app.save

    uri = URI.parse("https://api.monkeylearn.com/v2/extractors/ex_y7BPYzNG/extract/")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    request = Net::HTTP::Post.new(uri.request_uri)
    # Set POST data
    request.body = {text_list: [@bulb.description]}.to_json
    request.add_field("Content-Type", "application/json")
    request.add_field("Authorization", "token c956c6be34d90185c5eab3c04a8f58416259aa67")
    # parse the monkeylearn respons
    response = JSON.parse http.request(request).body
    response_array = response["result"].first

    keywords = Array.new

    response_array.each do |response|
      keywords << response["keyword"]
    end

    keywords.each do |keyword|
      k = Keyword.new
      k.bulb_id = @bulb.id
      k.content = keyword
      k.save
    end

    picture_results = Unsplash::Photo.search(keywords.sample)
      if picture_results.count != 0
        picture_sample = picture_results.sample
        @bulb.picture = picture_sample.urls["small"]
        @bulb.big_picture = picture_sample.urls["regular"]
        @bulb.save
        @app.picture = @bulb.picture
        @app.save
    end


    respond_to do |format|
      if @app.save
        format.html { redirect_to bulbs_url }
        format.json { render :show, status: :created, location: @app }
      else
        format.html { render :new }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apps/1
  # PATCH/PUT /apps/1.json
  def update

    @app.update(app_params)
    @app.save

    @bulb = Bulb.find_by(:id => @app.bulb_id)
    @bulb.title = params[:app][:title]
    @bulb.description = params[:app][:description]
    @bulb.target = params[:app][:target]
    @bulb.category = "app"
    @bulb.ref_id = @app.id
    @bulb.user_id = current_user.id
    @bulb.save


    uri = URI.parse("https://api.monkeylearn.com/v2/extractors/ex_y7BPYzNG/extract/")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    request = Net::HTTP::Post.new(uri.request_uri)
    # Set POST data
    request.body = {text_list: [@bulb.description]}.to_json
    request.add_field("Content-Type", "application/json")
    request.add_field("Authorization", "token c956c6be34d90185c5eab3c04a8f58416259aa67")
    # parse the monkeylearn respons
    response = JSON.parse http.request(request).body
    response_array = response["result"].first

    keywords = Array.new

    response_array.each do |response|
      keywords << response["keyword"]
    end

    keywords.each do |keyword|
      k = Keyword.new
      k.bulb_id = @bulb.id
      k.content = keyword
      k.save
    end



    respond_to do |format|
      if @app.save
        format.html { redirect_to bulbs_url }
        format.json { render :show, status: :ok, location: @app }
      else
        format.html { render :edit }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app.destroy
    respond_to do |format|
      format.html { redirect_to apps_url, notice: 'App was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app
      @app = App.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_params
      params.require(:app).permit(:title, :target, :description, :picture, :big_picture, :bulb_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/bulbs_helper.rb
module BulbsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <h4><%= f.text_field(:title, :class => "comment_input",:placeholder => "NAME YOUR BULB (eg. BULBZ)") %></h4>
  <h4>is an <span class="bulb_type">APP</span> that helps</h4>
  <h4><%= f.text_field(:target, :class => "comment_input", :placeholder => "DEFINE AN AUDIENCE (eg. IDEA JUNKIES)") %></h4>
  <h4><%= f.text_area(:description, :class => "text_area_small2", :placeholder => "Decribe it in your own words.") %></h4>
  <%= f.submit("CREATE APP BULB", :class => "submit_button comment_button", data: {disable_with: "Starting Machine Learning..."}) %>


<!--   <div class="field">
    <%= f.label :title %><br>

  </div>
  <div class="field">
    <%= f.label :target %><br>

  </div>
  <div class="field">
    <%= f.label :description %><br>

  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div> -->
<% end %>

app/views/apps/edit.html.erb
<div class="row">


<div class="col-sm-12">

<h1 id="add_app_title" style="font-family: 'Mr Dafoe', cursive; font-size: 80px; letter-spacing: 1px; text-align: center; padding: 0px 60px 0px 60px; font-weight: bolder; margin-top: 0px; margin-bottom: 0px; line-height: 90px; color: white">Your bulb's title</h1>

</div>

</div>

<div class="row">

<div class="grid-item2 col-sm-8 col-sm-offset-2" style="margin-top: 20px; padding: 90px">

  <%= render 'form' %>



</div>

</div>

<script type="text/javascript">

  $(function() {

    $("#app_title").focusout( function(e) {
    var content = e.target.value
    $('#add_app_title').text(content);

    });


  });
</script>

app/views/apps/index.html.erb
<div class="">

<div class="grid">
<div class="grid-sizer"></div>
<% @apps.reverse.each do |app| %>
    <div class="grid-item">

      <% if app.picture != nil %>
      <div class="row bulb_hl">
        <img src="<%= app.picture %>" width="100%">
      </div>
      <% end %>

      <div class="row bulb_hl" style="padding-top: 0px; padding-bottom: 0px">
        <div class="col-xs-12" style="padding: 0px;">
          <h4 style="margin-bottom: 20px;" class="index_mega"><span style="width: 100%"><%= app.title %></span></h4>
<!--           <img src="http://40.media.tumblr.com/4acc2a446cc63f3a52353a6c673391b1/tumblr_nm6y9hzrla1roigg6o1_1280.png" width="100%" style="margin-bottom: 20px;"> -->
        </div>
      </div>

      <div class="row bulb_hl" style="padding-top: 0px">
          <div class="col-xs-2">
            <h4 style="margin-bottom: 0px; padding-top: 15px;">An</h4>
          </div>
          <div class="col-xs-5">
            <h4 style="margin-bottom: 0px;"><span class="index_mega_color">APP</span></h4>
          </div>
          <div class="col-xs-5">
            <h4 style="margin-bottom: 0px; padding-top: 15px;">that helps</h4>
          </div>
      </div>

      <div class="row bulb_hl" style="padding-top: 0px; padding-bottom: 0px">
        <h4 class="index_mega"><span ><%= app.target %></span></h4>
        <h4 style="margin: 20px 0px 0px 0px;"><%= app.description %></h4>
      </div>


    </div>
<% end %>


</div>


</div>

<div class="fut" style="display: none">







<p id="notice"><%= notice %></p>

<h1>Listing Apps</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Target</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= app.title %></td>
        <td><%= app.target %></td>
        <td><%= app.description %></td>
        <td><%= app.picture %></td>
        <td><%= link_to 'Show', app %></td>
        <td><%= link_to 'Edit', edit_app_path(app) %></td>
        <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App', new_app_path %>

</div>

app/views/apps/new.html.erb
<div class="row">


<div class="col-sm-12">

<h1 id="add_app_title" style="font-family: 'Mr Dafoe', cursive; font-size: 80px; letter-spacing: 1px; text-align: center; padding: 0px 60px 0px 60px; font-weight: bolder; margin-top: 0px; margin-bottom: 0px; line-height: 90px; color: white">Your bulb's title</h1>

</div>

</div>

<div class="row">

<div class="grid-item2 col-sm-8 col-sm-offset-2" style="margin-top: 20px; padding: 90px">

  <%= render 'form' %>



</div>

</div>

<script type="text/javascript">

  $(function() {

    $("#app_title").focusout( function(e) {
    var content = e.target.value
    $('#add_app_title').text(content);

    });


  });
</script>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @app.title %>
</p>

<p>
  <strong>Target:</strong>
  <%= @app.target %>
</p>

<p>
  <strong>Description:</strong>
  <%= @app.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @app.picture %>
</p>

<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BULBZ - STORE, SHARE AND TAG YOUR BEST IDEAS</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>



<link href='https://fonts.googleapis.com/css?family=Lato:400,300,700,900,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Just+Another+Hand|Mr+Dafoe' rel='stylesheet' type='text/css'>



</head>
<body>

<div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav" style="padding: 25px 10px 20px 10px;">
<!--               <li>
                <% if current_user.present? %>
                  <img class = "img img-circle" src="<%= current_user.profile_picture %>" style="width: 30%">
                <% else %>
                  <img class = "img img-circle" src="https://s3.eu-central-1.amazonaws.com/mybulbz/icons/bulb1_round.png" style="width: 30%">
                <% end %>
              </li> -->
                <li class="sidebar-brand" style="text-align: center; padding: 50px 0px 50px 0px">
                    <a href="/bulbs" style="font-family: 'Mr Dafoe', cursive; font-size: 80px; letter-spacing: 1px; text-align: center">
                        Bulbz <!-- <i class="fa fa-lightbulb-o"></i> -->
                    </a>
                </li>
                <li style="margin-top: 40px;">
                    <a href="/bulbs">All blbz</a>
                </li>
              <!--   <li style="">
                   <a href="/apps">All apps(<%= App.all.count %>)</a>
                </li>
                <li style="">
                   <a href="/platforms">All platforms(<%= Platform.count %>)</a>
                </li> -->
                <li style="">
                    <% if current_user.present? %>
                    <a href="#">Your blbz</a>
                    <% end %>
                </li>
<!--                 <li style="">
                    <a href="#">Your private blbz</a>
                </li> -->

             <!--    <li style="">
                  <%= link_to 'New Bulb', new_bulb_path %>
                </li>

                <li style="">
                  <%= link_to 'New App', new_app_path %>
                </li>

                <li style="">
                  <%= link_to 'New Platform', new_platform_path %>
                </li>
                <li style="">
                  <%= link_to 'New Service', new_service_path %>
                </li>
                                <li style="">
                  <%= link_to 'New Shop', new_shop_path %>
                </li> -->


                <li>
<!--                   <button type="button" class="btn btn-bulb" data-toggle="modal" data-target="#myModal">
                  <img class = "img img-circle" src="https://s3.eu-central-1.amazonaws.com/mybulbz/icons/bulb1_round_pink.png" style="width: 60%;">
                  </button> -->
                  <a href="" style="color: #FB375D" data-toggle="modal" data-target="#myModal">New bulb</a>
                </li>

                <li>
                  <%= link_to("AI Cloud", keywords_url) %>
                </li>

                <li id="menu_aus" style="margin-top: 30px; display: none">
                <a href=""><span style="color: white; background-color: black; padding: 20px;">HIDE MENU</span></a>
                </li>



                <li style="margin-top: 50px; padding-bottom: 50px; border-bottom: 1px solid grey; padding-top: 50px; border-top: 1px solid grey">
                <% if current_user %>
                  <div class="row">
                    <div class="col-sm-12">
                      <img src="<%= current_user.profile_picture %>" class="img img-circle" width="80px">
                      <p style="margin-bottom: 0px; margin-top: 20px;"><%= current_user.name %></p>
                      <%= link_to "Sign Out", signout_path %>
                    </div>
                  </div>

                  <% else %>
                    <%= link_to "Sign in with Facebook", "/auth/facebook" %>
                  <% end %>
                </li>

                <li style="margin-top: 50px">
                  <a href="">About</a>
                </li>
                <li>
                  <a href="">Blog</a>
                </li>
                <li>
                  <a href="">Imprint</a>
                </li>



            </ul>
        </div>
        <!-- /#sidebar-wrapper -->










        <!-- Page Content -->
        <div id="page-content-wrapper">



            <div class="container-fluid">


                <div class="row">

<!--                                         <nav class="navbar navbar-default" id="start_nav">

                                            <div class="navbar-header">
                                              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                                <span class="sr-only">Toggle navigation</span>
                                                <span class="icon-bar"></span>
                                                <span class="icon-bar"></span>
                                                <span class="icon-bar"></span>
                                              </button>
                                            </div>
                                            <div id="navbar" class="collapse navbar-collapse">
                                              <div class="row" style="height: 30px;">
                                                  <div class="col-sm-8"></div>
                                                  <div class="col-sm-4" style="padding-top: 5px;">
                                                      <a href="" style="color: grey;">Facebook Login</a>
                                                  </div>
                                              </div>

                                            </div>

                                        </nav> -->


<!-- MODAL -->

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="padding: 60px">
      <div class="modal-header" style="margin-top: 30px;">
  <!--       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
                    <a href="#" style="font-family: 'Mr Dafoe', cursive; font-size: 30px; letter-spacing: 1px; text-align: center; color: black">
                        My idea is ...  <!-- <i class="fa fa-lightbulb-o"></i> -->
                    </a>
      </div>
      <div class="modal-body">
        <a href="/apps/new"><h4 style="margin-bottom: 0px; margin-top: 0px; text-align: center; margin-left: 50px; margin-right: 50px" class="index_mega_color"><span>AN APP</span></h4></a>
        <a href="/services/new"><h4 style="margin-bottom: 0px; margin-top: 10px; text-align: center; margin-left: 50px; margin-right: 50px" class="index_mega_color_service"><span>A SERVICE</span></h4></a>
        <a href="/shops/new"><h4 style="margin-bottom: 0px; margin-top: 10px; text-align: center; margin-left: 50px; margin-right: 50px" class="index_mega_color_shop"><span>A SHOP</span></h4></a>
          <a href="/platforms/new"><h4 style="margin-bottom: 50px; margin-top: 10px; text-align: center; margin-left: 50px; margin-right: 50px" class="index_mega_color_platform"><span>A PLATFORM</span></h4></a>
      </div>

    </div>
  </div>
</div>

<!-- END OF MODAL -->






                    <div class="" style="padding: 30px 30px 80px 30px;">


<div class="mob_top_nav">
<div class="row">
  <div class="col-xs-4">
    <a href="/bulbs" style="font-family: 'Mr Dafoe', cursive; font-size: 40px; letter-spacing: 1px; text-align: center; color: black; font-weight: bolder">
        Bulbz <!-- <i class="fa fa-lightbulb-o"></i> -->
    </a>
  </div>
  <div class="col-xs-4"></div>
  <div class="col-xs-4" style="padding-top: 15px; text-align: right;">
    <a href="" id="menu_ein"><span style="color: white; background-color: black; padding: 20px;">MENU</span></a>

  </div>
</div>

</div>




                        <%= yield %>
<!--                         <a href="#menu-toggle" class="" id="menu-toggle">Toggle Menu</a> -->
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>


<script src="https://unpkg.com/masonry-layout@4.0/dist/masonry.pkgd.js"></script>
<script src="https://unpkg.com/imagesloaded@4.1/imagesloaded.pkgd.min.js"></script>

</body>
</html>